// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(refrain_coreFFI)
import refrain_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_refrain_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_refrain_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureRefrainCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Mobile-facing handle that owns one `eval::Evaluator`. Thin wrapper: every
 * method forwards to the evaluator. The `Mutex` provides the interior
 * mutability uniffi's `&self` methods need (the evaluator's chunk methods are
 * `&mut self`) and is safe because uniffi shares this object as an `Arc`.
 */
public protocol RefrainCoreProtocol: AnyObject, Sendable {
    
    /**
     * `eval::Evaluator::advance_phase`: end the current phase now, enter the
     * next; past the last phase transitions to `stopped`. Returns false if
     * already stopped. (Clinician "Next →".)
     */
    func advancePhase()  -> Bool
    
    /**
     * `eval::Evaluator::current_phase`: snapshot of the phase the most recent
     * chunk ran under (aligned with the taps).
     */
    func currentPhase()  -> PhaseInfo
    
    /**
     * `eval::Evaluator::hold`: extend a `timed_with_floor` phase past its floor
     * (`hold(false)` re-arms). Returns true if it took effect.
     */
    func hold(held: Bool)  -> Bool
    
    /**
     * `eval::Evaluator::last_taps`: the most recent chunk's internal computed values —
     * keys like `input/raw`, `derive/<name>`, `threshold/<name>`, `reward/continuous`,
     * `output/<channel>` (booleans encoded as 0.0/1.0). For clinician observation /
     * live tuning. Empty before the first chunk. (BTreeMap → HashMap so uniffi maps it
     * to a Swift `[String: Double]` / Kotlin `Map`.)
     */
    func lastTaps()  -> [String: Double]
    
    /**
     * `eval::Evaluator::set_clock_frozen`: freeze/resume the phase clock on any
     * phase type (transport pause); orthogonal to output muting.
     */
    func setClockFrozen(frozen: Bool) 
    
    /**
     * `eval::Evaluator::set_control`: live-retune a clinician control in place,
     * preserving streaming state. An unknown name yields
     * `RefrainError::UnknownControl` (the FFI analogue of Python's `KeyError`).
     */
    func setControl(name: String, value: Double) throws 
    
    /**
     * `eval::Evaluator::start`: enter warmup (or run). Call before the first
     * `step_chunk_events`. `skip_warmup` jumps straight to `run`.
     */
    func start(skipWarmup: Bool) 
    
    /**
     * Process one chunk and emit feedback `Event`s. uniffi has no 2-D type, so
     * the chunk arrives as a flat, row-major `(n_samples * n_channels)` buffer
     * plus `n_channels`; it is reshaped into rows via the shared
     * `eval::rows_from_flat` helper (same reshape contract as the pyo3 path)
     * and forwarded to the unchanged `step_chunk_events`.
     */
    func stepChunkEvents(chunk: [Double], nChannels: UInt32)  -> [Event]
    
    /**
     * `eval::Evaluator::stop`: end the session.
     */
    func stop() 
    
}
/**
 * Mobile-facing handle that owns one `eval::Evaluator`. Thin wrapper: every
 * method forwards to the evaluator. The `Mutex` provides the interior
 * mutability uniffi's `&self` methods need (the evaluator's chunk methods are
 * `&mut self`) and is safe because uniffi shares this object as an `Arc`.
 */
open class RefrainCore: RefrainCoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_refrain_core_fn_clone_refraincore(self.pointer, $0) }
    }
    /**
     * Build from the IR-JSON wire format plus the host's runtime sample rate
     * and channel layout. Deserializes the IR via the existing serde
     * `ir::Protocol`; deserialization errors map to `RefrainError::InvalidIr`.
     */
public convenience init(irJson: String, sampleRateHz: Double, channelNames: [String])throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeRefrainError_lift) {
    uniffi_refrain_core_fn_constructor_refraincore_new(
        FfiConverterString.lower(irJson),
        FfiConverterDouble.lower(sampleRateHz),
        FfiConverterSequenceString.lower(channelNames),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_refrain_core_fn_free_refraincore(pointer, $0) }
    }

    

    
    /**
     * `eval::Evaluator::advance_phase`: end the current phase now, enter the
     * next; past the last phase transitions to `stopped`. Returns false if
     * already stopped. (Clinician "Next →".)
     */
open func advancePhase() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_advance_phase(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * `eval::Evaluator::current_phase`: snapshot of the phase the most recent
     * chunk ran under (aligned with the taps).
     */
open func currentPhase() -> PhaseInfo  {
    return try!  FfiConverterTypePhaseInfo_lift(try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_current_phase(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * `eval::Evaluator::hold`: extend a `timed_with_floor` phase past its floor
     * (`hold(false)` re-arms). Returns true if it took effect.
     */
open func hold(held: Bool) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_hold(self.uniffiClonePointer(),
        FfiConverterBool.lower(held),$0
    )
})
}
    
    /**
     * `eval::Evaluator::last_taps`: the most recent chunk's internal computed values —
     * keys like `input/raw`, `derive/<name>`, `threshold/<name>`, `reward/continuous`,
     * `output/<channel>` (booleans encoded as 0.0/1.0). For clinician observation /
     * live tuning. Empty before the first chunk. (BTreeMap → HashMap so uniffi maps it
     * to a Swift `[String: Double]` / Kotlin `Map`.)
     */
open func lastTaps() -> [String: Double]  {
    return try!  FfiConverterDictionaryStringDouble.lift(try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_last_taps(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * `eval::Evaluator::set_clock_frozen`: freeze/resume the phase clock on any
     * phase type (transport pause); orthogonal to output muting.
     */
open func setClockFrozen(frozen: Bool)  {try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_set_clock_frozen(self.uniffiClonePointer(),
        FfiConverterBool.lower(frozen),$0
    )
}
}
    
    /**
     * `eval::Evaluator::set_control`: live-retune a clinician control in place,
     * preserving streaming state. An unknown name yields
     * `RefrainError::UnknownControl` (the FFI analogue of Python's `KeyError`).
     */
open func setControl(name: String, value: Double)throws   {try rustCallWithError(FfiConverterTypeRefrainError_lift) {
    uniffi_refrain_core_fn_method_refraincore_set_control(self.uniffiClonePointer(),
        FfiConverterString.lower(name),
        FfiConverterDouble.lower(value),$0
    )
}
}
    
    /**
     * `eval::Evaluator::start`: enter warmup (or run). Call before the first
     * `step_chunk_events`. `skip_warmup` jumps straight to `run`.
     */
open func start(skipWarmup: Bool)  {try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_start(self.uniffiClonePointer(),
        FfiConverterBool.lower(skipWarmup),$0
    )
}
}
    
    /**
     * Process one chunk and emit feedback `Event`s. uniffi has no 2-D type, so
     * the chunk arrives as a flat, row-major `(n_samples * n_channels)` buffer
     * plus `n_channels`; it is reshaped into rows via the shared
     * `eval::rows_from_flat` helper (same reshape contract as the pyo3 path)
     * and forwarded to the unchanged `step_chunk_events`.
     */
open func stepChunkEvents(chunk: [Double], nChannels: UInt32) -> [Event]  {
    return try!  FfiConverterSequenceTypeEvent.lift(try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_step_chunk_events(self.uniffiClonePointer(),
        FfiConverterSequenceDouble.lower(chunk),
        FfiConverterUInt32.lower(nChannels),$0
    )
})
}
    
    /**
     * `eval::Evaluator::stop`: end the session.
     */
open func stop()  {try! rustCall() {
    uniffi_refrain_core_fn_method_refraincore_stop(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRefrainCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = RefrainCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> RefrainCore {
        return RefrainCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: RefrainCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RefrainCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: RefrainCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRefrainCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> RefrainCore {
    return try FfiConverterTypeRefrainCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRefrainCore_lower(_ value: RefrainCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeRefrainCore.lower(value)
}




/**
 * Mirror of `eval::Event` / `eval_.Event`: one unit of evaluator output.
 * `value` is the per-chunk mean for value channels and `None` for discrete
 * events. Re-exposed as a uniffi record so Swift/Kotlin get a plain value
 * type; the conversion is a field-for-field move, no logic.
 */
public struct Event {
    public var timestampS: Double
    public var channel: String
    public var kind: String
    public var value: Double?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(timestampS: Double, channel: String, kind: String, value: Double?) {
        self.timestampS = timestampS
        self.channel = channel
        self.kind = kind
        self.value = value
    }
}

#if compiler(>=6)
extension Event: Sendable {}
#endif


extension Event: Equatable, Hashable {
    public static func ==(lhs: Event, rhs: Event) -> Bool {
        if lhs.timestampS != rhs.timestampS {
            return false
        }
        if lhs.channel != rhs.channel {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(timestampS)
        hasher.combine(channel)
        hasher.combine(kind)
        hasher.combine(value)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEvent: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Event {
        return
            try Event(
                timestampS: FfiConverterDouble.read(from: &buf), 
                channel: FfiConverterString.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                value: FfiConverterOptionDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Event, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.timestampS, into: &buf)
        FfiConverterString.write(value.channel, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterOptionDouble.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEvent_lift(_ buf: RustBuffer) throws -> Event {
    return try FfiConverterTypeEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEvent_lower(_ value: Event) -> RustBuffer {
    return FfiConverterTypeEvent.lower(value)
}


/**
 * Mirror of `eval::PhaseSnapshot` / `eval_.Evaluator.current_phase`: the phase
 * the most recent chunk ran under (aligned with `last_taps`). `index == -1`
 * once terminal / before any chunk.
 */
public struct PhaseInfo {
    public var index: Int64
    public var name: String?
    public var mode: String?
    public var outputMuted: Bool
    public var block: String?
    public var remainingS: Double?
    public var clockFrozen: Bool
    public var held: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(index: Int64, name: String?, mode: String?, outputMuted: Bool, block: String?, remainingS: Double?, clockFrozen: Bool, held: Bool) {
        self.index = index
        self.name = name
        self.mode = mode
        self.outputMuted = outputMuted
        self.block = block
        self.remainingS = remainingS
        self.clockFrozen = clockFrozen
        self.held = held
    }
}

#if compiler(>=6)
extension PhaseInfo: Sendable {}
#endif


extension PhaseInfo: Equatable, Hashable {
    public static func ==(lhs: PhaseInfo, rhs: PhaseInfo) -> Bool {
        if lhs.index != rhs.index {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.mode != rhs.mode {
            return false
        }
        if lhs.outputMuted != rhs.outputMuted {
            return false
        }
        if lhs.block != rhs.block {
            return false
        }
        if lhs.remainingS != rhs.remainingS {
            return false
        }
        if lhs.clockFrozen != rhs.clockFrozen {
            return false
        }
        if lhs.held != rhs.held {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(index)
        hasher.combine(name)
        hasher.combine(mode)
        hasher.combine(outputMuted)
        hasher.combine(block)
        hasher.combine(remainingS)
        hasher.combine(clockFrozen)
        hasher.combine(held)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePhaseInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PhaseInfo {
        return
            try PhaseInfo(
                index: FfiConverterInt64.read(from: &buf), 
                name: FfiConverterOptionString.read(from: &buf), 
                mode: FfiConverterOptionString.read(from: &buf), 
                outputMuted: FfiConverterBool.read(from: &buf), 
                block: FfiConverterOptionString.read(from: &buf), 
                remainingS: FfiConverterOptionDouble.read(from: &buf), 
                clockFrozen: FfiConverterBool.read(from: &buf), 
                held: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PhaseInfo, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.index, into: &buf)
        FfiConverterOptionString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.mode, into: &buf)
        FfiConverterBool.write(value.outputMuted, into: &buf)
        FfiConverterOptionString.write(value.block, into: &buf)
        FfiConverterOptionDouble.write(value.remainingS, into: &buf)
        FfiConverterBool.write(value.clockFrozen, into: &buf)
        FfiConverterBool.write(value.held, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhaseInfo_lift(_ buf: RustBuffer) throws -> PhaseInfo {
    return try FfiConverterTypePhaseInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePhaseInfo_lower(_ value: PhaseInfo) -> RustBuffer {
    return FfiConverterTypePhaseInfo.lower(value)
}


/**
 * Errors surfaced across the FFI boundary. Currently the only fallible step
 * is deserializing the IR-JSON wire format. `Display`/`Error` are implemented
 * by hand to avoid pulling in `thiserror` just for one variant.
 */
public enum RefrainError: Swift.Error {

    
    
    /**
     * The IR-JSON string could not be deserialized into a `Protocol`.
     */
    case InvalidIr(message: String
    )
    /**
     * `set_control` was called with a name that is not a declared control
     * (mirrors the Python evaluator raising `KeyError`).
     */
    case UnknownControl(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRefrainError: FfiConverterRustBuffer {
    typealias SwiftType = RefrainError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RefrainError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidIr(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .UnknownControl(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RefrainError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidIr(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .UnknownControl(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRefrainError_lift(_ buf: RustBuffer) throws -> RefrainError {
    return try FfiConverterTypeRefrainError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRefrainError_lower(_ value: RefrainError) -> RustBuffer {
    return FfiConverterTypeRefrainError.lower(value)
}


extension RefrainError: Equatable, Hashable {}




extension RefrainError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceDouble: FfiConverterRustBuffer {
    typealias SwiftType = [Double]

    public static func write(_ value: [Double], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterDouble.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Double] {
        let len: Int32 = try readInt(&buf)
        var seq = [Double]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterDouble.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEvent: FfiConverterRustBuffer {
    typealias SwiftType = [Event]

    public static func write(_ value: [Event], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEvent.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Event] {
        let len: Int32 = try readInt(&buf)
        var seq = [Event]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEvent.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringDouble: FfiConverterRustBuffer {
    public static func write(_ value: [String: Double], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterDouble.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: Double] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: Double]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterDouble.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_refrain_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_advance_phase() != 31310) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_current_phase() != 36666) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_hold() != 38295) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_last_taps() != 62853) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_set_clock_frozen() != 49829) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_set_control() != 31390) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_start() != 44094) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_step_chunk_events() != 4919) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_method_refraincore_stop() != 57124) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_refrain_core_checksum_constructor_refraincore_new() != 6650) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureRefrainCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all